services:
  json-diff:
    build: .
    image: json-diff
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    container_name: json-diff
